version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_ncapas
    environment:
      POSTGRES_DB: soporte_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_ncapas
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/soporte_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
